"""One macro per day, because 275 days cannot be 275 hand-written BUILD files.

`aoc_day()` is the Bazel equivalent of what `days/_template` plus
`members = ["*"]` do for cargo: it turns a directory that follows the
repo's layout convention into a full set of targets. The difference is that
cargo infers the targets from the filesystem and Bazel needs them declared,
so the declaration is generated (see tools/gen_day_build.py) rather than
written.

Targets produced for a day `2015-12-06`, given `c_api = True`:

    //days/2015-12-06:lib          rust_library (rlib)          — the solution
    //days/2015-12-06:test         rust_test                    — its unit tests
    //days/2015-12-06:bin          rust_binary                  — runs the puzzle input
    //days/2015-12-06:cdylib       rust_shared_library          — the loadable object
    //days/2015-12-06:header       generated aoc_2015_12_06.h   — cbindgen output
    //days/2015-12-06:c_api        cc_library (hdrs + cdylib)   — what a C caller deps on

The last two are the edge `just` cannot express. In days/justfile the
header/consumer relationship is a recipe dependency —
`swift-demo day: (bindgen day)` — which *re-runs* cbindgen every time. Here
it is a file dependency: the header is an output, the cc_library consumes
it, and a consumer rebuilds if and only if the generated bytes changed.
"""

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load(
    "@rules_rust//rust:defs.bzl",
    "rust_binary",
    "rust_library",
    "rust_shared_library",
    "rust_test",
)

# Every day inherits these from days/Cargo.toml's [workspace.package].
EDITION = "2024"

def _crate_ident(day):
    """2015-12-06 -> aoc_2015_12_06, matching the justfile's `tr - _`."""
    return "aoc_" + day.replace("-", "_")

def aoc_day(
        day,
        deps = [],
        dev_deps = [],
        build_script = False,
        build_script_deps = [],
        build_script_data = [],
        crate_features = [],
        cc_deps = [],
        variant = None,
        variant_features = [],
        variant_cc_deps = [],
        c_api = False,
        crate_name = None,
        proc_macro_deps = [],
        visibility = ["//visibility:public"]):
    """Declare one Advent of Code day.

    Args:
      day: the directory name, YYYY-MM-DD — validated the same way
        `just days new` validates it, because it lands in a crate name.
      deps: crate_universe labels, mirroring [dependencies].
      dev_deps: crate_universe labels, mirroring [dev-dependencies].
      build_script: True when the day has a build.rs. Five of nine days do,
        and every one of them finds a system library through pkg-config.
        See the cargo_build_script call below for what that costs here.
      build_script_deps: crate_universe labels, mirroring [build-dependencies].
      build_script_data: extra files the build script may read — C shim
        sources, mostly.
      crate_features: cargo features to enable on the default targets.
      cc_deps: cc_library labels linked into the Rust crate via `link_deps`
        (rules_rust deprecates C++ libraries in plain `deps`). This
        is the Bazel-native alternative to a build.rs that drives the `cc`
        crate: the C or C++ lives in a cc_library, the toolchain is Bazel's
        registered one, and rustc links the result. No build script runs.
      variant: name for a second set of targets built with extra features
        on — `:lib_<variant>`, `:test_<variant>`. The day's own feature
        gates are the reason: `cargo test --all-features` is one command,
        but Bazel has no "same target, more features" without either a
        second target or a config transition, and a second target is the
        one that stays readable.
      variant_features: features for that variant.
      variant_cc_deps: cc_library labels the variant needs.
      c_api: True when the day has src/c_api.rs and cbindgen.toml, i.e.
        exports itself to C. Adds the cdylib, the header and the cc_library.
      crate_name: override, for the one member that is not a day.
        `members = ["*"]` sweeps days/_template in alongside the real days —
        the same wrinkle days/Cargo.toml's `exclude` list exists to manage —
        and its crate is aoc-day-template, not aoc-YYYY-MM-DD. Passing this
        is what says "skip the date check", so a genuine typo in a real day
        still fails loudly.
      proc_macro_deps: crate_universe labels for proc-macro crates.
      visibility: default public; days are consumed by //bazel/... harnesses.
    """
    if crate_name == None:
        if len(day) != 10 or day[4] != "-" or day[7] != "-":
            fail("day must be YYYY-MM-DD, got '%s'" % day)
        ident = _crate_ident(day)
    else:
        ident = crate_name

    # ---- build.rs -----------------------------------------------------
    #
    # cargo_build_script compiles build.rs, runs it, and turns its stdout
    # (cargo:rustc-link-lib, cargo:rustc-cfg, …) into rustc flags — the same
    # protocol cargo implements.
    #
    # What it does NOT do is make the script hermetic. Every build.rs in this
    # repo resolves a system library by shelling out to `pkg-config`, and
    # inside Bazel's sandbox that is an undeclared read of an undeclared
    # binary against an undeclared PKG_CONFIG_PATH. It works here only
    # because the feature gates are off by default, so the scripts probe
    # nothing and emit only rerun-if-changed lines.
    #
    # Turning a feature on is where the model actually diverges: cargo's
    # answer is "be inside nix-shell", and Bazel's answer is a declared
    # cc_library for each of caca, tcc, hyperscan, ICU, chipmunk, duckdb,
    # yara and espeak-ng. Those are not small. docs/bazel-evaluation.md
    # takes this apart rather than pretending the line below covers it.
    build_deps = list(deps)
    if build_script:
        cargo_build_script(
            name = "build_script",
            srcs = ["build.rs"],
            crate_name = "build_script_%s" % ident,
            data = build_script_data,
            edition = EDITION,
            # No `tools`, no PKG_CONFIG_PATH, and deliberately no
            # `use_default_shell_env`: this is the honest version, and it is
            # honest only while no feature is enabled.
            visibility = ["//visibility:private"],
            deps = build_script_deps,
        )
        build_deps.append(":build_script")

    # src/**/*.rs, not an explicit list: a day grows modules (src/tcc.rs,
    # src/icu.rs) as it acquires C variants, and an explicit list is a
    # second place to remember. The glob is the one concession to cargo's
    # filesystem-inference model in this file.
    lib_srcs = native.glob(
        ["src/**/*.rs"],
        exclude = ["src/main.rs"],
        allow_empty = False,
    )

    rust_library(
        name = "lib",
        srcs = lib_srcs,
        crate_features = crate_features,
        crate_name = ident,
        edition = EDITION,
        proc_macro_deps = proc_macro_deps,
        visibility = visibility,
        deps = build_deps + cc_deps,
    )

    # `crate = ":lib"` compiles the library *again* with --test, which is
    # what picks up the `#[cfg(test)] mod tests` blocks living inside
    # src/c_api.rs and src/lib.rs. Same thing `cargo test` does.
    # compile_data = Cargo.toml is not decoration. rstest's proc macro reads
    # the manifest at expansion time (it looks up CARGO_MANIFEST_DIR to
    # confirm it is a declared dependency), and inside Bazel's sandbox a file
    # that is not a declared input does not exist. Without this line every
    # #[rstest] in the repo fails with "Could not find `Cargo.toml` in
    # manifest dir".
    #
    # Under cargo this class of bug is invisible, because the whole source
    # tree is always readable. It is the standard tax on moving a Rust
    # codebase into a sandboxed build: undeclared reads that used to work.
    rust_test(
        name = "test",
        crate = ":lib",
        compile_data = ["Cargo.toml"],
        # Restated, not inherited: rust_test(crate = ...) recompiles the
        # crate with --test but does not carry the library's crate_features
        # across. Leave it off and the #[cfg(feature = "…")] test modules
        # silently vanish — the target still passes, with fewer tests than
        # anyone reading the BUILD file would expect. Measured on
        # 2024-12-01: 5 tests instead of 9.
        crate_features = crate_features,
        edition = EDITION,
        link_deps = cc_deps,
        proc_macro_deps = proc_macro_deps,
        deps = build_deps + dev_deps,
    )

    # The feature-gated variant. In cargo this is `--features qsort,cpp`
    # against the same crate; here it is a second crate compiled from the
    # same sources, which is the honest cost of Bazel having no per-invocation
    # feature flag.
    if variant:
        rust_library(
            name = "lib_" + variant,
            srcs = lib_srcs,
            crate_features = crate_features + variant_features,
            crate_name = ident,
            edition = EDITION,
            link_deps = cc_deps + variant_cc_deps,
            proc_macro_deps = proc_macro_deps,
            visibility = visibility,
            deps = build_deps,
        )
        rust_test(
            name = "test_" + variant,
            crate = ":lib_" + variant,
            compile_data = ["Cargo.toml"],
            crate_features = crate_features + variant_features,
            edition = EDITION,
            link_deps = cc_deps + variant_cc_deps,
            proc_macro_deps = proc_macro_deps,
            deps = build_deps + dev_deps,
        )

    if native.glob(["src/main.rs"], allow_empty = True):
        rust_binary(
            name = "bin",
            srcs = ["src/main.rs"],
            edition = EDITION,
            # main.rs resolves inputs/<day>.txt through CARGO_MANIFEST_DIR.
            # Bazel sets that to an execroot path, so the file has to be a
            # runfile; the day still builds and tests without one, which is
            # the property .gitignore'd inputs require.
            data = ["//inputs:day_inputs"],
            visibility = visibility,
            deps = [":lib"] + build_deps,
        )

    if not c_api:
        return

    # ---- the FFI edge -------------------------------------------------

    rust_shared_library(
        name = "cdylib",
        srcs = lib_srcs,
        crate_name = ident,
        edition = EDITION,
        crate_features = crate_features,
        link_deps = cc_deps,
        proc_macro_deps = proc_macro_deps,
        visibility = visibility,
        deps = build_deps,
    )

    # Aimed at src/c_api.rs, not the crate root — the same rule days/justfile
    # documents, for the same reason: a day that also *imports* a C library
    # keeps those `extern "C"` declarations in their own module, and cbindgen
    # pointed at the crate root would redeclare somebody else's API into our
    # header.
    #
    # Under `just` that aim is a convention a recipe follows. Here it is an
    # input list: srcs names exactly the two files cbindgen may read, and the
    # sandbox makes reading anything else fail rather than silently widen the
    # header.
    native.genrule(
        name = "header",
        srcs = [
            "src/c_api.rs",
            "cbindgen.toml",
        ],
        outs = ["include/%s.h" % ident],
        cmd = " ".join([
            "$(execpath @tools_crates//:cbindgen__cbindgen)",
            "--config $(execpath cbindgen.toml)",
            "--output $@",
            "$(execpath src/c_api.rs)",
        ]),
        tools = ["@tools_crates//:cbindgen__cbindgen"],
        visibility = visibility,
    )

    # What every downstream language binds against. A cc_test, a Swift
    # modulemap and a Python cffi cdef all take this one label; none of them
    # names a -L path, an -rpath, or a dylib extension.
    #
    # That convenience is exactly the thing to be suspicious of in a workshop
    # whose subject is those flags — see docs/bazel-evaluation.md.
    cc_library(
        name = "c_api",
        hdrs = [":header"],
        includes = ["include"],
        linkstatic = False,
        visibility = visibility,
        deps = [":cdylib"],
    )
