#!/usr/bin/env python3
"""Emit days/<day>/BUILD.bazel from the Cargo manifests that already exist.

The premise of the Bazel overlay is that days/Cargo.toml stays authoritative:
`members = ["*"]` still registers a day by existing, `[workspace.dependencies]`
still pins every version once, and nothing is maintained twice. That premise
only holds if the BUILD files are derived rather than written, because
MODULE.bazel has no glob and Bazel has no filesystem inference.

So this is the Bazel half of `just days new`: cargo metadata in, one
`aoc_day()` call per day out. Run it after scaffolding a day; run it in CI
with --check to prove nobody hand-edited a generated file.

MODULE.bazel needs no edit for a new day — crate_universe resolves
`members = ["*"]` through cargo, so it lists only days/Cargo.toml.

    python3 tools/gen_day_build.py            # write
    python3 tools/gen_day_build.py --check    # fail if stale (CI)

At 9 days this is a convenience. At 275 it is the only thing standing
between the overlay and 275 files nobody keeps current.
"""

import argparse
import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DAYS = REPO / "days"

# Feature gates that need nothing outside this repo, and can therefore be
# BUILT here rather than merely declared.
#
# The other eight gates in days/ — caca, tcc, hyperscan, icu, chipmunk,
# duckdb, yara, espeak-ng — reach a system library through pkg-config, and
# under cargo the answer to "where does that come from" is shell.nix. Bazel
# has no such answer short of a cc_library per library; docs/bazel-evaluation.md
# is explicit that this table stops here for that reason, and not because the
# other eight are harder versions of the same thing.
#
# qsort:  libc, which every target links already — no build step at all.
# cpp:    one .cpp file in this repo. Under cargo it goes through build.rs
#         and the `cc` crate; here it is a cc_library on Bazel's own C++
#         toolchain, which is strictly less machinery.
# uthash: deliberately absent — header-only, but the header is a nix
#         package, so it belongs with the other eight.
SELF_CONTAINED = {
    "2024-12-01": {
        "variant": "cfeatures",
        "features": ["cpp", "qsort"],
        "cc_libraries": [
            {
                "name": "cpp_sort",
                "srcs": ["src/cpp_sort.cpp"],
                "linkstatic": True,
            },
        ],
    },
}

CC_LIBRARY_TEMPLATE = """cc_library(
    name = "%(name)s",
    srcs = %(srcs)s,
    linkstatic = %(linkstatic)s,
)

"""

HEADER = """# GENERATED by tools/gen_day_build.py — do not edit.
# Source of truth is this directory's Cargo.toml. Regenerate with:
#   python3 tools/gen_day_build.py

load("//tools:aoc.bzl", "aoc_day")

exports_files(["Cargo.toml"])

"""

CC_LOAD = 'load("@rules_cc//cc:defs.bzl", "cc_library")\n'


def label(dep_name):
    """cargo dependency name -> crate_universe label."""
    return '"@days_crates//:%s"' % dep_name


def render(day, deps, dev_deps, c_api, build_script, build_deps, build_data, crate_name=None):
    extra = SELF_CONTAINED.get(day)
    header = HEADER
    prelude = ""
    if extra and extra.get("cc_libraries"):
        header = HEADER.replace(
            'load("//tools:aoc.bzl", "aoc_day")',
            CC_LOAD.rstrip("\n") + '\nload("//tools:aoc.bzl", "aoc_day")',
        )
        for cc in extra["cc_libraries"]:
            prelude += CC_LIBRARY_TEMPLATE % {
                "name": cc["name"],
                "srcs": '["%s"]' % '", "'.join(cc["srcs"]),
                "linkstatic": "True" if cc.get("linkstatic") else "False",
            }
    lines = [header, prelude, "aoc_day(\n", '    day = "%s",\n' % day]
    if crate_name:
        lines.append('    crate_name = "%s",\n' % crate_name)
    if build_script:
        lines.append("    build_script = True,\n")
        if build_deps:
            lines.append("    build_script_deps = [\n")
            lines += ["        %s,\n" % label(d) for d in sorted(build_deps)]
            lines.append("    ],\n")
        if build_data:
            lines.append("    build_script_data = [\n")
            lines += ['        "%s",\n' % d for d in sorted(build_data)]
            lines.append("    ],\n")
    if c_api:
        lines.append("    c_api = True,\n")
    if extra:
        lines.append('    variant = "%s",\n' % extra["variant"])
        lines.append("    variant_features = [\n")
        lines += ['        "%s",\n' % f for f in extra["features"]]
        lines.append("    ],\n")
        if extra.get("cc_libraries"):
            lines.append("    variant_cc_deps = [\n")
            lines += ['        ":%s",\n' % c["name"] for c in extra["cc_libraries"]]
            lines.append("    ],\n")
    if deps:
        lines.append("    deps = [\n")
        lines += ["        %s,\n" % label(d) for d in sorted(deps)]
        lines.append("    ],\n")
    if dev_deps:
        lines.append("    dev_deps = [\n")
        lines += ["        %s,\n" % label(d) for d in sorted(dev_deps)]
        lines.append("    ],\n")
    lines.append(")\n")
    return "".join(lines)


def day_dirs():
    """Every workspace member, as cargo resolves `members = ["*"]`."""
    meta = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--no-deps"],
            cwd=DAYS,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    )
    out = []
    for pkg in meta["packages"]:
        d = pathlib.Path(pkg["manifest_path"]).parent
        out.append((d.name, d, pkg))
    return sorted(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    stale = []
    count = 0

    for name, path, pkg in day_dirs():
        deps, dev_deps, build_deps = set(), set(), set()
        for dep in pkg["dependencies"]:
            # build-dependencies are the build script's, not the crate's;
            # aoc_day() wires those through cargo_build_script instead.
            if dep["kind"] == "dev":
                dev_deps.add(dep["name"])
            elif dep["kind"] == "build":
                build_deps.add(dep["name"])
            elif dep["kind"] is None:
                deps.add(dep["name"])

        c_api = (path / "src" / "c_api.rs").exists() and (path / "cbindgen.toml").exists()
        build_script = (path / "build.rs").exists()

        # C shim sources a build script compiles (yara_shim.c, icu_shim.c)
        # are inputs to the script and have to be declared as such.
        build_data = sorted(
            str(p.relative_to(path)) for p in path.rglob("*.c")
        ) if build_script else []

        # The crate name cargo actually resolved, when it is not the one
        # aoc_day() would derive from the directory (days/_template).
        derived = "aoc_" + name.replace("-", "_")
        actual = pkg["name"].replace("-", "_")
        crate_name = None if actual == derived else actual

        text = render(
            name, deps, dev_deps, c_api, build_script, build_deps, build_data, crate_name
        )
        target = path / "BUILD.bazel"
        count += 1

        if args.check:
            current = target.read_text() if target.exists() else ""
            if current != text:
                stale.append(str(target.relative_to(REPO)))
        else:
            target.write_text(text)

    if args.check and stale:
        print("stale generated BUILD files:", file=sys.stderr)
        for s in stale:
            print("  " + s, file=sys.stderr)
        print("\nrun: python3 tools/gen_day_build.py", file=sys.stderr)
        return 1

    if not args.check:
        print("wrote %d BUILD.bazel files" % count)
    return 0


if __name__ == "__main__":
    sys.exit(main())
